update French translations
bcgov/shinyssdtools pull request #176
Opened 2024-06-26 23:07 UTC by sebdalgarno

see #175 , #174 
also update multi_ci arg which was now failing due to stricter ...

2024-06-26 23:07 UTC, sebdalgarno commented
waiting on joes confirmation regarding `ci_method`

2024-06-28 22:17 UTC, joethorley commented
Yes I can confirm that we should just go with the default `ci_method` (which is `"weighted_samples"`) but also you can drop `multi_est = TRUE` as this is  the new default.

2024-06-29 01:08 UTC, sebdalgarno commented
deployed to main poisson site -
will merge once BCANZ translations added - then merge into bcgov fork

2024-08-08 17:54 UTC, joethorley requested changes

2024-08-08 17:54 UTC, joethorley commented on data-raw/data.R
> +    french = "étiquette de changement"
```suggestion
    french = "Étiquette de changement"
```

Do we need this capitalized?

2024-08-08 17:54 UTC, joethorley commented on inst/extdata/user-fr.md
> +Cette application web estime la distribution de la sensibilité des espèces en fonction des données de concentration. L’application est conçue à partir ddu progiciel R [ssdtools](https://github.com/bc
```suggestion
Cette application web estime la distribution de la sensibilité des espèces en fonction des données de concentration. L’application est conçue à partir ddu progiciel R [ssdtools](https://github.com/bcgov/ssdtools), et partage les mêmes fonctions.
De plus amples informations sur les méthodes de ssdtools sont disponibles aux liens suivants [articles du site web] (https://bcgov.github.io/ssdtools/articles/).
```

2024-08-08 17:54 UTC, joethorley commented on inst/extdata/user-fr.md
> +Cette application web estime la distribution de la sensibilité des espèces en fonction des données de concentration. L’application est conçue à partir ddu progiciel R [ssdtools](https://github.com/bc
Can you put new sentences on new lines here and other places.

2024-08-08 17:54 UTC, joethorley requested changes
Looks great - I've added a few suggested edits for you to review.

2024-08-08 19:14 UTC, sebdalgarno commented on data-raw/data.R
> +    french = "étiquette de changement"
yes good catch

2024-08-08 20:56 UTC, joethorley approved these changes
looks great

2024-08-08 21:16 UTC, merged

2024-08-08 21:16 UTC, sebdalgarno commented
deployed to poisson site and tested